# Generated by Django 5.0.6 on 2024-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_root_parent',
            field=models.BooleanField(default=False),
        ),
    ]
