# Generated by Django 5.0.6 on 2024-10-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_service_is_root_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='icon',
            new_name='brand_icon',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner'),
        ),
    ]
